name: Docker Image CI

on:
  tags:
   - 'v*.*.*'

jobs:

  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Log in to DigitalOcean Container Registry
      uses: docker/login-action@v3
      with:
        registry: registry.digitalocean.com
        username: ${{secrets.DO_USERNAME}}
        password: ${{secrets.DO_ACCESS_TOKEN}}
    
    - name: Build the Docker image
      run: |
        docker build . --file Dockerfile --target prod --tag react-vite-project:{{github.ref_name}}
        docker tag react-vite-project:{{github.ref_name}} registry.digitalocean.com/private-docker-images/react-vite-project:{{github.ref_name}}

    - name: Push Docker Image to Digital Ocean Registry
      run: |
        docker push registry.digitalocean.com/private-docker-images/react-vite-project:{{github.ref_name}}
